extends RichTextLabel
@onready var context_text: RichTextLabel = %"context-text"

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	if ClassVariables.playerRace == "Felynx":
		if ClassVariables.playerDickSize == "Vagina":
			%"context-text".text = "You run your fingers through your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair and past your fuzzy ears, " + ClassVariables.playerHairColor.to_lower() + " tail swishing just behind you in your reflection as you stare into your narrow pupils in the mirror. Your slitted eyes are a lovely shade of " + ClassVariables.playerEyeColor.to_lower() + " and you admire your " + ClassVariables.playerStature.to_lower() + " figure briefly - eyes particularly trailing over your quim. Your " + ClassVariables.playerChestSize + " chest suits nicely, accomodating the rest of your figure."	
		else:
			%"context-text".text = "You run your fingers through your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair and past your fuzzy ears, " + ClassVariables.playerHairColor.to_lower() + " tail swishing just behind you in your reflection as you stare into your narrow pupils in the mirror. Your slitted eyes are a lovely shade of " + ClassVariables.playerEyeColor.to_lower() + " and you admire your " + ClassVariables.playerStature.to_lower() + " figure briefly - eyes particularly trailing over your " + ClassVariables.playerDickSize.to_lower() + " cock.  Your " + ClassVariables.playerChestSize + " chest suits nicely, accomodating the rest of your figure."	
	elif ClassVariables.playerRace == "Human":
		if ClassVariables.playerDickSize == "Vagina":
			%"context-text".text = "You run your fingers through your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair, staring into your " + ClassVariables.playerEyeColor.to_lower() + " eyes, tired as they are. You take a moment to admire your  " + ClassVariables.playerStature.to_lower() + " frame, eyes particularly trailing over your quim. Your " + ClassVariables.playerChestSize + " chest suits you nicely, accomodating the rest of your figure."
		else:
			%"context-text".text = "You run your fingers through your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair, staring into your " + ClassVariables.playerEyeColor.to_lower() + " eyes, tired as they are. You take a moment to admire your  " + ClassVariables.playerStature.to_lower() + " frame, eyes particularly trailing over your " + ClassVariables.playerDickSize.to_lower() + " cock. Your " + ClassVariables.playerChestSize + " chest suits you nicely, accomodating the rest of your figure."
	elif ClassVariables.playerRace == "Slyme":
		if ClassVariables.playerDickSize == "Vagina":
			%"context-text".text = "You stretch after you disrobe, your gelatenous frame bouncing in your reflection. Your bubbly and slick body attracts the eye no matter where it looks. Your " + ClassVariables.playerSkinColor.to_lower() + " candy like skin matches your... Hair? Your " + ClassVariables.playerHairLength.to_lower() + " hair is the same sweet bouncy texture and colour as the rest of you, and your " + ClassVariables.playerStature.to_lower() + " figure catches your eye, particularly around your " + ClassVariables.playerChestSize + " chest and your quim - the gooey texture prized by most of the galaxy."
		else: 
			%"context-text".text = "You stretch after you disrobe, your gelatenous frame bouncing in your reflection. Your bubbly and slick body attracts the eye no matter where it looks. Your " + ClassVariables.playerSkinColor.to_lower() + " candy like skin matches your... Hair? Your " + ClassVariables.playerHairLength.to_lower() + " hair is the same sweet bouncy texture and colour as the rest of you, and your " + ClassVariables.playerStature.to_lower() + " figure catches your eye, particularly around your " + ClassVariables.playerChestSize + " chest and your " + ClassVariables.playerDickSize.to_lower() + " cock - the gooey texture prized by most of the galaxy."
	elif ClassVariables.playerRace == "Vulpine":
		if ClassVariables.playerDickSize == "Vagina":
			%"context-text".text = "The hairs on your fluffy tail and ears stand on end as you disrobe, the cool air tracing along your skin. They're the same color as your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair. You stare into your " + ClassVariables.playerEyeColor.to_lower() + " eyes, reflecting their tiredness back at you. You take a moment to admire your " + ClassVariables.playerStature.to_lower() + " frame, eyes particularly trailing over your quim. Your " + ClassVariables.playerChestSize + " chest suits you nicely, accomodating the rest of your figure."
		else:
			%"context-text".text = "The hairs on your fluffy tail and ears stand on end as you disrobe, the cool air tracing along your skin. They're the same color as your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair. You stare into your " + ClassVariables.playerEyeColor.to_lower() + " eyes, reflecting their tiredness back at you. You take a moment to admire your " + ClassVariables.playerStature.to_lower() + " frame, eyes particularly trailing over your " + ClassVariables.playerDickSize.to_lower() + " cock. Your " + ClassVariables.playerChestSize + " chest suits you nicely, accomodating the rest of your figure."
	elif ClassVariables.playerRace == "Equine":
		if ClassVariables.playerDickSize == "Vagina":
			%"context-text".text = "Your large frame takes up the majority of the reflection, and you admire your figure top to bottom, eyes glancing over your " + ClassVariables.playerChestSize + " chest and down between your legs sports a gorgeous quim. Your eyes trail back up, catching your tired " + ClassVariables.playerEyeColor.to_lower() + " eyes in your reflection, your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair sits neatly atop your head."
		else:
			%"context-text".text = "Your large frame takes up the majority of the reflection, and you admire your figure top to bottom, eyes glancing over your " + ClassVariables.playerChestSize + " chest and down between your legs sports a large " + ClassVariables.playerDickSize.to_lower() + " equine cock intimidatingly hanging right where it belongs). Your eyes trail back up, catching your tired " + ClassVariables.playerEyeColor.to_lower() + " eyes in your reflection, your " + ClassVariables.playerHairLength.to_lower() + " " + ClassVariables.playerHairColor.to_lower() + " hair sits neatly atop your head."
